apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: appconnect-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-appconnect-11.5.1
  publisher: IBM
  image: acraueadevncisws01.azurecr.io/cpopen/appconnect-operator-catalog@sha256:79a9cb9b855d7ee1e10056e914df7aea6061d2cbffc7bfd6387a21b7fed76842
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
