apiVersion: v1
kind: Service
metadata:
  name: calculator-api-svc
  namespace: calculator # {{ .Values.namespace }}
  # annotations:
  #   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: calculator
spec:
  selector:
    tier: calculator-api
  ports:
    - protocol: TCP
      port: 80 # {{ .Values.api.servicePort }}
      targetPort: 5000
      name: http
  type: LoadBalancer # ClusterIP # {{ .Values.api.serviceType }}
