trigger:
  none

variables:
  buildConfiguration: Release
  projects: '**/*.csproj'
  testProjects: '**/*[Uu]nit[Tt]ests.csproj'

stages:
- stage: Build_Web_Api
  variables:
  - group: calculator-common
  jobs:
  - template: ../templates/build-web-app.yml
    parameters: 
      projects: $(projects)
      buildConfiguration: $(buildConfiguration)
      testProjects: $(testProjects)
      webProjName: $(webProjName)
- stage: Deploy_Web_Api_Dev
  variables:
  - group: calculator-dev
  - group: calculator-dev-kv
  jobs:
  - job: Deploy_Web_Api
    pool:
      vmImage: windows-latest
    steps:
    - template: ../templates/deploy-web-app.yml
      parameters: 
        azureSubscription: 'VSP'
        appName: $(appName)
        webProjName: $(webProjName)
    condition: succeeded()
