apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: mymachineset
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-machineset: mymachineset
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-machineset: mymachineset
    spec:
      providerSpec:
        value:
          apiVersion: azureproviderconfig.openshift.io/v1beta1
          kind: AzureMachineProviderSpec
          vmSize: Standard_D2s_v3
          image:
            resourceID: /resourceGroups/myResourceGroup/providers/Microsoft.Compute/images/myImage
          location: eastus
          osDisk:
            diskSizeGB: 128
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          userDataSecret:
            name: worker-user-data
          credentialsSecret:
            name: azure-cloud-credentials
          subnet:
            name: mySubnet
          networkResourceGroup: myNetworkResourceGroup
          publicIP: false
          vnet: myVnet
          servicePrincipalID: myServicePrincipalID
          servicePrincipalSecret: myServicePrincipalSecret