apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-files-dyn-pvc
  namespace: test-storage # Replace with your namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi # Specify the size 
  storageClassName: azurefile-csi