# update the secret when the storage account keys are rotated
apiVersion: v1
kind: Secret
metadata:
  name: azure-files-secret
type: Opaque
data:
  azurestorageaccountname: ${AZURE_SA_NAME}
  azurestorageaccountkey: ${AZURE_SA_KEY}