apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-disk-dyn-pvc
  namespace: test-storage # Replace with your namespace
  labels:
    app-lbl: pod-disk-dyn
  annotations:
    app-annotation: pod-disk-dyn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Specify the size of the disk
  storageClassName: managed-csi # Specify your storage class name here, "default" is often used for Azure Disk