apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-disk-pv
  labels:
    type: azure-disk
spec:
  capacity:
    storage: 5Gi # Specify the size of the disk. This should match the actual disk size.
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  azureDisk:
    kind: Managed
    diskName: disk-auea-dev-ncis-x01 # The name of your Azure Disk
    diskURI: /subscriptions/2ef01a24-f9c4-4a9f-bca8-7d0ca8fe11fa/resourcegroups/rg-auea-dev-ncis/providers/Microsoft.Compute/disks/disk-auea-dev-ncis-x01 # The URI for your Azure Disk
    fsType: ext4 # The filesystem type to use
