apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-files-static-pvc
  namespace: test-storage # Replace with your namespace
  labels:
    app-lbl: pod-files-static
  annotations:
    app-annotation: pod-files-static
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi # Specify the size of the disk
  selector:
    matchLabels:
      type: azure-files
  # storageClassName: ""