apiVersion: v1
kind: Pod
metadata:
  name: pod-files-static
  namespace: test-storage
  labels:
    files: fsaueadevdemox01
spec:
  containers:
  - name: nginx01
    image: nginx
    volumeMounts:
    - mountPath: "/mnt/azure"
      name: azure-files-volume
    resources: {}
  volumes:
  - name: azure-files-volume
    persistentVolumeClaim:
      claimName: azurefile-pvc # azure-files-static-pvc