trigger:
  none

stages:
- stage: Validate_Publish_ARM_Template
  variables:
  - group: calculator-common
  jobs:
  - template: ../templates/validate-publish-ARM-template.yml
    parameters: 
      azureSubscription: 'VSP'
      resourceGroup: $(resourceGroup)
      location: $(location)
      armTemplate: $(kvArmTemplate)
- stage: Deploy_KV_Dev
  variables:
  - group: calculator-dev
  jobs:
  - template: ../templates/deploy-kv-infra.yml
    parameters:
      azureSubscription: 'VSP'
      resourceGroup: $(resourceGroup)
      location: $(location)
      kvArmTemplate: $(kvArmTemplate)
      kvName: $(kvName)
