trigger:
  none

stages:
- stage: Validate_Publish_ARM_Template
  variables:
  - group: calculator-common
  jobs:
  - template: ../templates/validate-publish-ARM-template.yml
    parameters: 
      azureSubscription: 'VSP'
      resourceGroup: $(resourceGroup)
      location: $(location)
      armTemplate: $(webAppArmTemplate)
- stage: Deploy_Web_App_Dev
  variables:
  - group: calculator-dev
  jobs:
  - template: ../templates/deploy-web-app-infra.yml
    parameters:
      azureSubscription: 'VSP'
      resourceGroup: $(resourceGroup)
      location: $(location)
      webAppArmTemplate: $(webAppArmTemplate)
      planName: $(planNameUI)
      appName: $(appNameUI)
      skuName: $(skuNameUI)
      skuCapacity: $(skuCapacityUI)
- stage: Deploy_Web_App_Test
  variables:
  - group: calculator-test
  jobs:
  - deployment: test_deploy
    environment: calculator-test
  - template: ../templates/deploy-web-app-infra.yml
    parameters:
      azureSubscription: 'VSP'
      resourceGroup: $(resourceGroup)
      location: $(location)
      webAppArmTemplate: $(webAppArmTemplate)
      planName: $(planNameUI)
      appName: $(appNameUI)
      skuName: $(skuNameUI)
      skuCapacity: $(skuCapacityUI)
