apiVersion: v1
kind: Service
metadata:
  name: calculator-ui-svc
  namespace: calculator # {{ .Values.namespace }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: calculator
spec:
  selector:
    tier: calculator-ui
  ports:
    - protocol: TCP
      port: 80 # {{ .Values.ui.servicePort }}
      targetPort: 80
      name: http
  type: LoadBalancer # {{ .Values.ui.serviceType }}
