apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: $secretProviderClassName
spec:
  provider: azure
  secretObjects:
    - secretName: ${secretName}
      type: kubernetes.io/tls
      data: 
        - objectName: ${keyVaultCertificateName}
          key: tls.key
        - objectName: ${keyVaultCertificateName}
          key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ${clientId}
    keyvaultName: ${keyVaultName}
    objects: |
      array:
        - |
          objectName: ${keyVaultCertificateName}
          objectType: secret
    tenantId: ${tenantId}